server.port: 8081
spring.application.name: apse-open-service

logging.path: ${user.home}/logs

com.alipay.sofa.rpc:
  bolt.port: 22002
  registry.address: zookeeper://192.168.206.182:2181
#  registry.address: local://${user.home}/logs/localRegistry.reg