server.port: 8080
spring.application.name: apse-center-service

# 建立连接超时时间
server.connection-timeout: 3000
# 请求超时时间
spring.mvc.async.request-timeout: 3000

# tomcat
server.tomcat:
  uri-encoding: UTF-8
  max-connections: 10000 #最大连接数
  accept-count: 3000 #线程数量
  max-threads: 400 #最大并发数
  min-spare-threads: 17 #线程池最大核心线程数

# gzip
server.compression:
  enabled: true
  mime-types: application/json,application/xml,text/html,text/xml,text/plain

# 日志
logging.path: ${user.home}/logs

# sofaRPC
com.alipay.sofa.rpc:
  bolt.port: 22000
  registry.address: zookeeper://192.168.206.182:2181
#  registry.address: local://${user.home}/logs/localRegistry.reg

# redis
spring.redis:
  database: 5
  host: 127.0.0.1
  password: 123456
  port: 6379
  timeout: 3000
  lettuce:
    pool.max-active: 100
    pool.max-wait: 30000
    pool.max-idle: 20
    pool.min-idle: 0

# mysql
spring.datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/archives?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
  username: root
  password: 123456
  druid:
    initial-size: 8 #初始化时建立物理连接的个数
    max-active: 10 #最大连接池数量
    min-idle: 8 #最小连接池数量
    max-wait: 60000 #获取连接时最大等待时间，单位毫秒
    filters: stat,wall #开启监控统计,防御sql注入过滤器
    web-stat-filter.enabled: true #是否开启druid数据库监控
    stat-view-servlet.enabled: true #是否开启druid监控页面
    stat-view-servlet.allow :
    stat-view-servlet.login-username: admin
    stat-view-servlet.login-password: admin123
    filter.stat.log-slow-sql: true #是否开启慢sql查询监控
    filter.stat.slow-sql-millis: 1 #慢SQL执行时间

# mybatis
mybatis:
  type-aliases-package: com.returncode.apseboot.center.*.entity
  mapper-locations: classpath:mapper/*Mapper.xml