server.port: 8080
spring.application.name: apse-center-service

logging.path: ${user.home}/logs

com.alipay.sofa.rpc:
  bolt.port: 22000
  registry.address: zookeeper://192.168.206.182:2181
#  registry.address: local://${user.home}/logs/localRegistry.reg
